name: Upload website to S3

on:
    push:
        branches:
            - main
    
jobs:
    deploy:
        runs-on: ubuntu-lastest
        steps:
            - uses: actions/checkout@master
            - uses: jakejarvis/s3-sync-action@master
        with:
            args: --acl public-read --follow-symlinks --delete
        env:
            AWS-S3-BUCKET: ${{ secrets.AWS-S3-BUCKET }}
            AWS-ACCESS-KEY-ID: ${{secrets.AWS-ACCESS-KEY-ID}}
            AWS-SECRET-ACCESS-KEY: ${{secrets.AWS-SECRET-ACCESS-KEY}}
            AWS-REGION: 'us-east-1'
            SOURCE-DIR: 'website'